accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        views.user_login,
        name="login",
    ),
    path(
        "logout/",
        auth_views.logout_then_login,
        name="logout",
    ),
    path("profile/", views.profile, name="profile")
]

historia_clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("historia/", include("historia.urls")),
    path("accounts/", include("accounts.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", RedirectView.as_view(url="historia/")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "input input-bordered w-full max-w-xs"
            })

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "input input-bordered w-full max-w-xs"
            })

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import Group
from .forms import UserRegisterForm, UserLoginForm


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # Add user to 'pacientes' group
            user = form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            # asignar grupo al usuario
            print(user)
            group = Group.objects.get(name="medicos")
            print(group)
            user.groups.add(group)

            return redirect("historia:index")
        # else:
        #     for error in form.errors:
        #         print(error)
        #         messages.error(request, f"{error}: {form.errors[error]}")
    else:
        form = UserRegisterForm()
    return render(request, "accounts/register.html", {"form": form})



def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("historia:index")
    else:
        form = UserLoginForm()
    return render(request, "accounts/login.html", {"form": form})


def profile(request):
    context = {}
    context["user"] = request.user
    print(request.user, type(request.user))

    return render(request, "accounts/profile.html")

accounts/templates/accounts/login.html
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Iniciar sesión</title>
    {% tailwind_css %}
  </head>
  <body>
    <main class="flex flex-col items-center justify-center space-y-3">
      <h2 class="text-2xl font-bold">Iniciar sesión</h2>
      <form method="post" class="flex flex-col items-center justify-center space-y-4 max-w-xs mx-auto">
        {% csrf_token %}

        <div class="flex flex-col items-center justify-center">
          <label for="id_username">Nombre de usuario:</label>
          {{ form.username }}
        </div>
        <div class="flex flex-col items-center justify-center">
          <label for="id_password">Contraseña:</label>
          {{ form.password }}
        </div>
        {{ field.errors }}


        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
      </form>
      
      <p>¿No tienes una cuenta? Crea una</p>

      <a href="{% url 'accounts:register' %}" class="btn btn-neutral">Registrarse</a>
    </main>
  </body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cerrar Sesión</title>
</head>
<body>
    {{form.as_p}}
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'historia/base.html' %}

{% block content %}
<main class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Perfil de Usuario</h1>
    <p class="mb-2">¡Bienvenido(a), {{ user.username }}!</p>
    {% comment %} <p class="mb-2">Nombre: {{ user.first_name }}</p>
    <p class="mb-2">Apellido: {{ user.last_name }}</p> {% endcomment %}
    <p class="mb-2">Email: {{ user.email }}</p>

    <p class="mb-2">Permisos:</p>
    <ul class="list-disc ml-6">
        {% for permission in user.get_all_permissions %}
            <li>{{ permission }}</li>
        {% endfor %}
    </ul>
</main>
{% endblock %}

accounts/templates/accounts/register.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registro</title>
    {% tailwind_css %}
  </head>
  <body>
    <div class="container flex flex-col items-center">
      <h2 class="text-2xl font-bold">Registro</h2>
      <form method="post" class="flex flex-col items-center justify-center space-y-3">
        {% csrf_token %}
        <div class="flex flex-col items-center justify-center">
          <label for="id_username">Nombre de usuario:</label>
          {{ form.username }}
        </div>
        <div class="flex flex-col items-center justify-center">
          <label for="id_email">Email:</label>
          {{ form.email }}
        </div>
        <div class="flex flex-col items-center justify-center">
          <label for="id_password1">Contraseña:</label>
          {{ form.password1 }}
        </div>
        <div class="flex flex-col items-center justify-center">
          <label for="id_password2">Confirmar Contraseña:</label>
          {{ form.password2 }}
        </div>

        {% if form.errors %}
          <div class="flex flex-col items-center justify-center" role="alert">
            <strong class="font-bold">¡Ups!</strong>
            <span class="block sm:inline">{{ form.errors }}</span>
          </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">Registrarse</button>

        <p>¿Ya tienes una cuenta? Inicia sesión</p>
        <a href="{% url 'accounts:login' %}" class="btn btn-neutral">Iniciar sesión</a>
      </form>
    </div>
  </body>
</html>