accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        views.user_login,
        name="login",
    ),
    path(
        "logout/",
        auth_views.logout_then_login,
        name="logout",
    ),
    path("profile/", views.profile, name="profile")
]

historia/urls.py
from django.urls import path

from . import views
from log import logger

logger.info("Se ha cargado el módulo de URLs")

app_name = "historia"
urlpatterns = [
    path("", views.index, name="index"),
    path("crear_paciente/", views.crear_paciente, name="crear_paciente"),
    path("tabla_pacientes/", views.tabla_pacientes, name="tabla_pacientes"),
    path("editar_paciente/<int:pk>/", views.editar_paciente, name="editar_paciente"),
    path("eliminar_paciente/<int:pk>/", views.eliminar_paciente, name="eliminar_paciente"),
    path("generar_tabla_pacientes/", views.generar_tabla_pacientes, name="generar_tabla_pacientes"),
    path("crear_historia/<int:pk>/", views.crear_historia, name="crear_historia"),
    path("ver_historias/<str:paciente_id>/", views.ver_historias, name="ver_historias"),
    path("editar_historia/<int:pk>/", views.editar_historia, name="editar_historia"),
]

historia_clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("historia/", include("historia.urls")),
    path("accounts/", include("accounts.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", RedirectView.as_view(url="historia/")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

historia/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User


# Create your models here.
class Paciente(models.Model):
    generos_validos = {
        "": "Seleccione un género",
        "M": "Masculino",
        "F": "Femenino",
    }

    # Indigenas, Afrocolombianos, Raizales, Rom
    etnias_validas = {
        "": "Seleccione una etnia",
        "ninguna": "Ninguna",
        "indigena": "Indígena",
        "afrocolombiano": "Afrocolombiano",
        "raizal": "Raizal",
        "rom": "Rom",
    }

    id = models.AutoField(primary_key=True)
    identificacion = models.CharField(
        max_length=20, unique=True, verbose_name="Identificación"
    )
    nombre_completo = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(blank=True)
    genero = models.CharField(
        max_length=1, choices=generos_validos, verbose_name="Género"
    )
    direccion = models.CharField(max_length=100, blank=True, verbose_name="Dirección")
    telefono = models.CharField(max_length=20, verbose_name="Teléfono")
    etnia = models.CharField(max_length=50, choices=etnias_validas)

    medico = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return f"{self.nombre_completo} ({self.identificacion})"

    def save(self, *args, **kwargs):
        self.nombre_completo = self.nombre_completo.upper()
        self.direccion = self.direccion.upper()
        return super().save(*args, **kwargs)

    def get_edad(self):
        return date.today().year - self.fecha_nacimiento.year


class HistoriaClinica(models.Model):
    grupos_antecedentes = {
        "": "Seleccione un grupo",
        "personal": "Personal",
        "familiar": "Familiar",
    }

    tipo_antecedentes = {
        "": "Seleccione un tipo",
        "quirurgico": "Quirúrgico",
        "alergico": "Alergico",
        "traumatico": "Traumático",
        "toxicologico": "Toxicológico",
    }

    id_historia = models.AutoField(primary_key=True)
    paciente = models.ForeignKey(
        Paciente, on_delete=models.CASCADE, to_field="identificacion", editable=True
    )
    grupo_antecedente = models.CharField(max_length=50, choices=grupos_antecedentes)
    tipo_antecedente = models.CharField(max_length=50, choices=tipo_antecedentes)
    fecha = models.DateField()
    descripcion = models.TextField(verbose_name="Descripción")
    habilitado = models.BooleanField(default=True)

    anotacion = models.TextField(
        blank=True, null=True, verbose_name="Anotación"
    )

    def __str__(self) -> str:
        return f"historia {self.paciente.nombre_completo}"

historia/forms.py
from django import forms
from .models import Paciente, HistoriaClinica
# from datetime import date


class PacienteForm(forms.ModelForm):
        # https://docs.djangoproject.com/en/5.0/ref/forms/widgets/#styling-widget-instances
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "input input-bordered w-full max-w-xs"
            })

    class Meta:
        model = Paciente
        fields = "__all__"
        exclude = ["medico"]
        widgets = {
            # "genero": forms.RadioSelect,
            # "etnia": forms.RadioSelect,
            "fecha_nacimiento": forms.DateInput(
                attrs={"type": "date"}, format="%Y-%m-%d"
            ),
        }



        error_messages = {
            "nombre_completo": {"required": "Por favor, ingrese un nombre"},
            "genero": {"required": "Por favor, seleccione un género"},
            "etnia": {"required": "Por favor, seleccione una etnia"},
        }

    # todo: organizar
    template_name = "historia/custom_form.html"



class CrearHistoriaClinicaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["grupo_antecedente"].widget.attrs.update({"class": "daisyui-select"})
        self.fields["tipo_antecedente"].widget.attrs.update({"class": "daisyui-select"})
        self.fields["fecha"].widget.attrs.update({"class": "input input-bordered w-full max-w-xs"})
        self.fields["descripcion"].widget.attrs.update({"class": "daisyui-textarea"})
        self.fields["habilitado"].widget.attrs.update({"class": "daisyui-checkbox"})

    class Meta:
        model = HistoriaClinica
        fields = "__all__"
        exclude = ["paciente", "anotacion"]
        widgets = {
            # "grupo_antecedente": forms.RadioSelect,
            # "tipo_antecedente": forms.RadioSelect,
            "fecha": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "descripcion": forms.Textarea(attrs={"rows": 5, "cols": 25}),
        }

    template_name = "historia/custom_form.html"


class EditarHistoriaClinicaForm(CrearHistoriaClinicaForm):
    class Meta:
        model = HistoriaClinica
        fields = "__all__"
        exclude = ["paciente"]
        widgets = {
            # "grupo_antecedente": forms.RadioSelect,
            # "tipo_antecedente": forms.RadioSelect,
            "fecha": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "descripcion": forms.Textarea(attrs={"rows": 5, "cols": 25}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["anotacion"].widget.attrs.update(
            {
                "class": "daisyui-textarea",
                "rows": "5",
                "cols": "25",
             }
        )

    template_name = "historia/custom_form.html"

historia/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required, permission_required
from .forms import EditarHistoriaClinicaForm, PacienteForm, CrearHistoriaClinicaForm
from .models import Paciente, HistoriaClinica
from django.core.exceptions import PermissionDenied


@login_required
def index(request: HttpRequest):
    return render(request, "historia/base.html")


@permission_required("historia.view_paciente", raise_exception=True)
def tabla_pacientes(request: HttpRequest):
    # context = {}
    # context["pacientes"] = Paciente.objects.all()
    # context["pacientes"] = Paciente.objects.filter(medico=request.user)
    # print(request.user)
    # context["pacientes"]

    return render(request, "historia/tabla_pacientes.html")


@permission_required("historia.add_paciente", raise_exception=True)
def crear_paciente(request: HttpRequest):
    if request.method == "POST":
        form = PacienteForm(request.POST)
        print(form.errors)
        if form.is_valid():
            paciente: Paciente = form.save(commit=False)
            paciente.medico = request.user
            paciente.save()
            return redirect("historia:tabla_pacientes")
    else:
        form = PacienteForm()
    return render(request, "historia/crear_paciente.html", {"form": form})


@permission_required("historia.change_paciente", raise_exception=True)
def editar_paciente(request: HttpRequest, pk: int):
    paciente = Paciente.objects.get(pk=pk)
    if request.method == "POST":
        form = PacienteForm(request.POST, instance=paciente)
        if form.is_valid():
            form.save()
            return redirect("historia:tabla_pacientes")
    else:
        form = PacienteForm(instance=paciente)
    return render(request, "historia/editar_paciente.html", {"form": form})


@permission_required("historia.add_historiaclinica", raise_exception=True)
def crear_historia(request: HttpRequest, pk: int):
    paciente = Paciente.objects.get(pk=pk)
    if request.method == "POST":
        form = CrearHistoriaClinicaForm(request.POST)
        if form.is_valid():
            historia = form.save(commit=False)
            historia.paciente = paciente
            historia.save()
            return redirect(
                "historia:ver_historias", paciente_id=paciente.identificacion
            )
    else:
        form = CrearHistoriaClinicaForm()
    return render(
        request,
        "historia/crear_historia.html",
        {"form_historia": form, "paciente": paciente},
    )


@permission_required("historia.view_historiaclinica", raise_exception=True)
def ver_historias(request: HttpRequest, paciente_id: str):
    historias = HistoriaClinica.objects.filter(paciente__identificacion=paciente_id)
    context = {
        "historias": historias,
        "paciente": Paciente.objects.get(identificacion=paciente_id),
    }
    return render(request, "historia/ver_historias.html", context)


@permission_required("historia.change_historiaclinica", raise_exception=True)
def editar_historia(request: HttpRequest, pk: int):
    historia = HistoriaClinica.objects.get(pk=pk)
    paciente = historia.paciente
    if request.method == "POST":
        form = EditarHistoriaClinicaForm(request.POST, instance=historia)
        if form.is_valid():
            form.save()
            return redirect(
                "historia:ver_historias",
                paciente_id=historia.paciente.identificacion,
                permanent=True,
            )
    else:
        form = EditarHistoriaClinicaForm(instance=historia)
    return render(
        request, "historia/editar_historia.html", {"form": form, "paciente": paciente}
    )


@permission_required("historia.delete_paciente", raise_exception=True)
def eliminar_paciente(request: HttpRequest, pk: int):
    paciente = Paciente.objects.get(pk=pk)
    paciente.delete()
    return redirect("historia:tabla_pacientes")


def generar_tabla_pacientes(request: HttpRequest):
    context = {}
    # context["pacientes"] = Paciente.objects.all()
    context["pacientes"] = Paciente.objects.filter(medico=request.user)
    identificacion = request.GET.get("identificacion")

    if identificacion:
        context["pacientes"] = context["pacientes"].filter(
            identificacion__startswith=identificacion
        )

    return render(request, "historia/tabla.html", context)

historia/templates/historia/base.html
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Clinica</title>
    {% tailwind_css %}
    {% block extra_head %}

    {% endblock %}
  </head>
  <body>
    <nav class="navbar bg-base-300 mx-auto p-4">
      <div class="navbar-start">
        <span class="text-lg font-bold text-primary"><a href="{% url 'historia:index' %}">Inicio</a></span>
      </div>
      <div class="navbar-center">
        <ul class="flex space-x-10">
          <li>
            <a href="{% url 'historia:tabla_pacientes' %}">Lista de Pacientes</a>
          </li>
          <li>
            <a href="{% url 'historia:crear_paciente' %}">Crear Paciente</a>
          </li>
        </ul>
      </div>
      <div class="navbar-end space-x-4">
        <div>
          Usuario:
          <span class="font-bold"><a href="{% url 'accounts:profile' %}">{{ user }}</a></span>
        </div>

        {% if user.is_authenticated %}
          <div>
            <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Cerrar Sesión</button>
            </form>
          </div>
        {% else %}
          <div>
            <a href="{% url 'accounts:login' %}">Iniciar Sesión</a>
          </div>
        {% endif %}
        <button id="theme-toggle" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
            <path d="M12 2.25a.75.75 0 0 1 .75.75v2.25a.75.75 0 0 1-1.5 0V3a.75.75 0 0 1 .75-.75ZM7.5 12a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM18.894 6.166a.75.75 0 0 0-1.06-1.06l-1.591 1.59a.75.75 0 1 0 1.06 1.061l1.591-1.59ZM21.75 12a.75.75 0 0 1-.75.75h-2.25a.75.75 0 0 1 0-1.5H21a.75.75 0 0 1 .75.75ZM17.834 18.894a.75.75 0 0 0 1.06-1.06l-1.59-1.591a.75.75 0 1 0-1.061 1.06l1.59 1.591ZM12 18a.75.75 0 0 1 .75.75V21a.75.75 0 0 1-1.5 0v-2.25A.75.75 0 0 1 12 18ZM7.758 17.303a.75.75 0 0 0-1.061-1.06l-1.591 1.59a.75.75 0 0 0 1.06 1.061l1.591-1.59ZM6 12a.75.75 0 0 1-.75.75H3a.75.75 0 0 1 0-1.5h2.25A.75.75 0 0 1 6 12ZM6.697 7.757a.75.75 0 0 0 1.06-1.06l-1.59-1.591a.75.75 0 0 0-1.061 1.06l1.59 1.591Z" />
          </svg>
        </button>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
  </body>

  <script>
    const themeToggle = document.getElementById('theme-toggle')
    const currentTheme = localStorage.getItem('theme')
    if (currentTheme === 'light') {
      document.documentElement.setAttribute('data-theme', 'light')
    }
    
    themeToggle.addEventListener('click', () => {
      if (document.documentElement.getAttribute('data-theme') === 'dark') {
        document.documentElement.setAttribute('data-theme', 'light')
        localStorage.setItem('theme', 'light')
      } else {
        document.documentElement.setAttribute('data-theme', 'dark')
        localStorage.setItem('theme', 'dark')
      }
    })
  </script>

  <script>
    // Todos los boton con la clase boton_confirmar deben mostrar un mensaje de confirmación
    const botones = document.querySelectorAll('.boton_confirmar')

    botones.forEach((boton) => {
      boton.addEventListener('click', function (event) {
        const confirmacion = confirm('¿Está seguro de que desea guardar los cambios?')
        if (!confirmacion) {
          event.preventDefault()
        }
      })
    })

  </script>
</html>

historia/templates/historia/crear_historia.html
{% extends 'historia/base.html' %}

{% block title %}
  Crear Antecedente
{% endblock %}

{% block content %}
  <div class="w-full max-w-80 mx-auto my-5">
    <h1 class="text-2xl font-bold">Crear antecedente</h1>
    {{ paciente }}

    <form method="post" class="bg-base-200 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      {% csrf_token %}
      {{ form_historia }}
      <button type="submit" class="btn btn-primary boton_confirmar">Guardar</button>
    </form>
  </div>
{% endblock %}

historia/templates/historia/crear_paciente.html
{% extends 'historia/base.html' %}
{% block title %}
  Crear Paciente
{% endblock %}

{% block content %}

<div class="w-full max-w-80 mx-auto my-5"/>
<form id="pacienteForm" method="POST" class="bg-base-200 shadow-md rounded px-8 pt-6 pb-8 mb-4">
  {% csrf_token %}
  {{ form }}
  {% comment %} <input type="submit" value="Submit" class="btn btn-primary boton_confirmar"/> {% endcomment %}
  <button type="submit" class="btn btn-primary boton_confirmar">Guardar</button>
</form>
</div>
{% endblock %}

historia/templates/historia/custom_form.html
{% for field in form %}
{{ field.errors }}
  <div class="mb-4">
    <p>
      {{ field.label_tag }}
    </p>
    <p>
      {{ field }}
    </p>
  </div>
{% endfor %}

{% comment %}

{{ field.errors }}
<label for="{{ field.id_for_label }}" class="my-label-css-class">{{ field.label }}</label>
<input id="{{ field.id_for_label }}" class="my-field-css-class" type="text" name="{{ field.html_name }}" value="{{ field.value|default:'' }}" />

{% endcomment %}

historia/templates/historia/editar_historia.html
{% extends 'historia/base.html' %}

{% block title %}
  Editar Historia
{% endblock %}

{% block content %}
  <div class="w-full max-w-80 mx-auto my-5">
    <h1 class="text-2xl font-bold">Editar Antecedente</h1>
    {{ paciente }}

    <form method="post" class="bg-base-200 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn btn-primary boton_confirmar">Guardar</button>
    </form>
  </div>
{% endblock %}

historia/templates/historia/editar_paciente.html
{% extends 'historia/base.html' %}

{% block title %}
  Editar pacientes
{% endblock %}

{% block content %}
  {{ paciente }}

<div class="w-full max-w-80 mx-auto my-5"/>

  <h1 class="text-2xl font-bold">Editar paciente</h1>

  <form method="post" class="bg-base-200 shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="boton_confirmar btn btn-primary">Guardar</button>
  </form>
</div>

{% endblock %}

historia/templates/historia/tabla.html
<table class="table">
  <thead class="text-xs uppercase bg-base-300">
    <tr>
      <th>Identificacion</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Sexo</th>
      <th>Etnia</th>
      <th>Acciones</th>
      <th>Historia Clinica</th>
    </tr>
  </thead>
  <tbody>
    {% for paciente in pacientes %}
      <tr class="hover">
        <td>{{ paciente.identificacion }}</td>
        <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">{{ paciente.nombre_completo }}</th>
        <td>{{ paciente.get_edad }}</td>
        <td>{{ paciente.get_genero_display }}</td>
        <td>{{ paciente.etnia }}</td>
        <td>
          <a class="font-medium text-blue-600 dark:text-blue-500 hover:underline" href="{% url 'historia:editar_paciente' paciente.id %}">Editar</a>
          <a class="font-medium text-red-600 dark:text-red-500 hover:underline" href="{% url 'historia:eliminar_paciente' paciente.id %}">Eliminar</a>
        </td>
        <td>
          <a class="font-medium text-blue-600 dark:text-blue-500 hover:underline" href="{% url 'historia:ver_historias' paciente.identificacion %}">Ver</a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

historia/templates/historia/tabla_pacientes.html
{% extends 'historia/base.html' %}

{% block title %}
  Tabla pacientes
{% endblock %}

{% block extra_head %}
  <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
  <main class="container mx-auto p-4">
    <h1 class="text-2xl font-bold gap-4">Pacientes</h1>

    <form action="" class="gap-4 mb-4">
      <div class="flex flex-row space-x-5">
        <div class="flex flex-col items-center">
          <label for="identificacion" class="label">Buscar por Identificacion</label>
          <input type="text" class="input input-bordered w-full max-w-xs" name="identificacion" hx-get="{% url 'historia:generar_tabla_pacientes' %}" hx-trigger="keyup changed delay:500ms" hx-target="#contenedorTabla" placeholder="Buscar..." />
        </div>
      </div>
    </form>

    <div id="contenedorTabla" class="relative overflow-x-auto shadow-md sm:rounded-lg" hx-get="{% url 'historia:generar_tabla_pacientes' %}" hx-trigger="load"></div>
  </main>
{% endblock %}

historia/templates/historia/ver_historias.html
{% extends 'historia/base.html' %}

{% block title %}
  Lista Historas
{% endblock %}

{% block content %}
  <main class="container mx-auto p-4 space-y-5">
    {% comment %} botton para crear nuevo antecedente {% endcomment %}
    <a href="{% url 'historia:crear_historia' paciente.pk %}" class="btn btn-primary">Nuevo antecedente</a>

    <ul class="menu bg-base-200 rounded-box">
      <li class="menu-title text-gray-400">Antecedentes de {{ paciente.nombre_completo }}</li>
      {% for historia in historias %}
        <li class="{% if not historia.habilitado %} disabled {% endif %}">
          <a href="{% url 'historia:editar_historia' historia.id_historia %}">
            <ul>
              <li>{{ forloop.counter }}.</li>
              <li>
                <p>
                  <span class="font-bold">Grupo antecedente:</span>{{ historia.grupo_antecedente }}
                </p>
              </li>
              <li>
                <p>
                  <span class="font-bold">Tipo antecedente:</span>{{ historia.tipo_antecedente }}
                </p>
              </li>
              <li>
                <p>
                  <span class="font-bold">Fecha:</span>{{ historia.fecha }}
                </p>
              </li>
            </ul>
          </a>
        </li>
      {% endfor %}
    </ul>
  </main>
{% endblock %}